- name: pacotes
  apt:
    update_cache: yes
    pkg:
      - sssd
      - krb5-user

- name: configura krb5.conf
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf

- name: configura sssd
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: 0600
  notify: reinicia sssd

#- name: home directory
#  lineinfile:
#    path: /etc/pam.d/common-session
#    line: 'session    required    pam_mkhomedir.so skel=/etc/skel/ umask=0077'

# passar para outra role
- name: pam mkhomedir
  lineinfile:
    path: /etc/pam.d/common-session
    line: session optional pam_mkhomedir.so

